Cleaned up the program flow. Added an ls option. Fixed the shebang.

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,29 +1,32 @@
-#/bin/bash
+#!/bin/bash
 ########################################################################
 #                                                                      #
 # backup                                                               #
-# Automate rotating rsync backups                                      #
+# Automate rotating rsync backups to offline devices                   #
 #                                                                      #
 # Credit to Mike Rubel for describing the process.                     #
 # http://www.mikerubel.org/computers/rsync_snapshots/                  #
 #                                                                      #
 # The process in this script differers from most rotating rsync        #
 # scripts because it makes no attempt to rotate checkpoints in a       #
-# hierarchal manner. Simply if the most recent checkpoint of a type is #
-# older than expected, the checkpoints are rotated and a new one is    #
+# hierarchal manner. Simply, if the most recent checkpoint of a type   #
+# is older than expected, the checkpoints are rotated and a new one is #
 # created.                                                             #
 #                                                                      #
 ########################################################################
+IFS=' '
+PATH=/usr/sbin:/usr/bin:/sbin:/bin
+
 OK=YES
 CONFIG='/etc/backup.conf'
 
-if [ -f "${CONFIG}" ]; then
+if [[ -f "${CONFIG}" ]]; then
     . "${CONFIG}"
 else
     echo "**** BACKUP CONFIGURATION FILE MISSING (${CONFIG}) ****" 1>&2
     echo '' 1>&2
     OK=NO
-fi;
+fi
 
 [[ -v INSTANT ]] || INSTANT=24
 [[ -v DAILY   ]] || DAILY=7
@@ -35,7 +38,7 @@ if ! [[ -v DEVICE ]]; then
     DEVICE=''
     echo '**** DEVICE IS NOT IS NOT CONFIGURED ****' 1>&2
     echo 'EXAMPLE:' 1>&2
-    echo "DEVICE='/dev/disk/by-partlabel/rsnapshot'"
+    echo "DEVICE='/dev/disk/by-partlabel/partlabel'" 1>&2
     echo '' 1>&2
     OK=NO
 fi
@@ -44,16 +47,7 @@ if ! [[ -v MOUNT ]]; then
     MOUNT=''
     echo '**** MOUNT IS NOT IS NOT CONFIGURED ****' 1>&2
     echo 'EXAMPLE:' 1>&2
-    echo "MOUNT='/var/local/backup'"
-    echo '' 1>&2
-    OK=NO
-fi
-
-if ! [[ -v ROOT ]]; then
-    ROOT=''
-    echo '**** ROOT IS NOT IS NOT CONFIGURED ****' 1>&2
-    echo 'EXAMPLE:' 1>&2
-    echo 'ROOT="${MOUNT}/`hostname`"'
+    echo "MOUNT='/var/local/backup'" 1>&2
     echo '' 1>&2
     OK=NO
 fi
@@ -62,7 +56,7 @@ if ! [[ -v HEAD ]]; then
     HEAD=''
     echo '**** HEAD IS NOT IS NOT CONFIGURED ****' 1>&2
     echo 'EXAMPLE:' 1>&2
-    echo 'HEAD="${ROOT}/head"'
+    echo 'HEAD="${MOUNT}/`hostname`/head"' 1>&2
     echo '' 1>&2
     OK=NO
 fi
@@ -83,7 +77,7 @@ if ! [[ -v RSYNC ]]; then
     OK=NO
 fi
 
-
+[[ -v ROOT ]] || ROOT=`dirname "${HEAD}"`
 [[ -v DEVICE_REAL ]] || DEVICE_REAL=`readlink -f "${DEVICE}"`
 
 ########################################################################
@@ -95,7 +89,6 @@ fnConfig() {
     echo "YEARLY  : ${YEARLY}"
     echo "DEVICE  : ${DEVICE} (${DEVICE_REAL})"
     echo "MOUNT   : ${MOUNT}"
-    echo "ROOT    : ${ROOT}"
     echo "HEAD    : ${HEAD}"
 }
 
@@ -108,17 +101,18 @@ fnHelp() {
     echo '  df                Display disk usage on backup device'
     echo '  du                Display space consumed by backups'
     echo '  diff              Dry-run with verbose output'
+    echo '  ls                List all backups'
     echo '  mount [dir [rw]]  Mount the backup device'
     echo '  umount            Unmount the backup device'
 }
 
 fnIsAvailable() {
-    test -b "${1}"
+    [[ -b "${1}" ]]
     return $?
 }
 
 fnIsMounted() {
-    grep -qs "^$1 " /proc/mounts;
+    grep -qs "^$1 " /proc/mounts
     return $?
 }
 
@@ -126,14 +120,14 @@ fnMount() {
     local RESULT
     local MNT
     local OPT
-    if [ "$1" = "" ]; then
+    if [[ "$1" = "" ]]; then
         MNT="${MOUNT}"
         OPT="rw"
     else
         MNT="${1}"
         OPT="ro"
 
-        if [ "${2}" = "rw" ]; then
+        if [[ "${2}" = "rw" ]]; then
             OPT="rw"
         fi
     fi
@@ -144,13 +138,18 @@ fnMount() {
     elif fnIsMounted "${DEVICE_REAL}"; then
         echo "**** ${DEVICE} IS ALREADY MOUNTED ****" 1>&2
         RESULT=1
-    elif [ ! -d "${MNT}" ]; then
-        echo "**** ${MNT} DOES NOT EXIST ****" 1>&2
+    elif [[ ! -d "${MNT}" ]]; then
+        echo "**** MOUNT POINT ${MNT} DOES NOT EXIST ****" 1>&2
         RESULT=1
     else
         echo "mount -o ${OPT} ${DEVICE_REAL} ${MNT}"
         mount -o "${OPT}" "${DEVICE_REAL}" "${MNT}"
-        RESULT=$?
+        if [[ "$?" -ne "0" ]]; then
+            echo '**** ERROR MOUNTING ${DEVICE} ****' 1>&2
+            RESULT=1
+        else
+            RESULT=0
+        fi
     fi
     return "${RESULT}"
 }
@@ -162,7 +161,7 @@ fnUmount() {
     else
         echo "umount ${DEVICE_REAL}"
         umount "${DEVICE_REAL}"
-        if [ "$?" -ne "0" ]; then
+        if [[ "$?" -ne "0" ]]; then
             echo '**** ERROR UNMOUNTING ${DEVICE} ****' 1>&2
             return 1
         else
@@ -183,7 +182,7 @@ fnDf() {
         if ! fnUmount; then
             RESULT=1
         fi
-    fi;
+    fi
     return "${RESULT}"
 }
 
@@ -193,20 +192,43 @@ fnDu() {
         RESULT=1
     else
         echo 'du -shc'
-        (
-            find "${ROOT}" -maxdepth 1 -type d -name "head"      -print 2>/dev/null
+        {
+            find "${HEAD}" -maxdepth 0 -type d                   -print 2>/dev/null
             find "${ROOT}" -maxdepth 1 -type d -name "instant.*" -print 2>/dev/null |sort
             find "${ROOT}" -maxdepth 1 -type d -name "daily.*"   -print 2>/dev/null |sort
             find "${ROOT}" -maxdepth 1 -type d -name "weekly.*"  -print 2>/dev/null |sort
             find "${ROOT}" -maxdepth 1 -type d -name "monthly.*" -print 2>/dev/null |sort
             find "${ROOT}" -maxdepth 1 -type d -name "yearly.*"  -print 2>/dev/null |sort
-        ) |xargs du -shc
+        } |xargs du -shc
         RESULT=$?
 
         if ! fnUmount; then
             RESULT=1
         fi
-    fi;
+    fi
+    return "${RESULT}"
+}
+
+fnLs() {
+    local RESULT
+    if ! fnMount "${MOUNT}" ro; then
+        RESULT=1
+    else
+        echo 'du -shc'
+        {
+            find "${HEAD}" -maxdepth 0 -type d                   -print 2>/dev/null
+            find "${ROOT}" -maxdepth 1 -type d -name "instant.*" -print 2>/dev/null |sort
+            find "${ROOT}" -maxdepth 1 -type d -name "daily.*"   -print 2>/dev/null |sort
+            find "${ROOT}" -maxdepth 1 -type d -name "weekly.*"  -print 2>/dev/null |sort
+            find "${ROOT}" -maxdepth 1 -type d -name "monthly.*" -print 2>/dev/null |sort
+            find "${ROOT}" -maxdepth 1 -type d -name "yearly.*"  -print 2>/dev/null |sort
+        } |xargs ls -fld
+        RESULT=$?
+
+        if ! fnUmount; then
+            RESULT=1
+        fi
+    fi
     return "${RESULT}"
 }
 
@@ -218,7 +240,7 @@ fnDiff() {
         local N=0
         for CMD in "${RSYNC[@]}"; do
             DIFF["${N}"]=`echo "${CMD}" |sed 's/rsync /rsync -n -v /'`
-            N=`expr ${N} + 1`
+            ((N++))
         done
     fi
 
@@ -228,7 +250,7 @@ fnDiff() {
         for CMD in "${DIFF[@]}"; do
             echo "${CMD}"
             $CMD
-            if [ "$?" -ne "0" ]; then
+            if [[ "$?" -ne "0" ]]; then
                 RESULT=1
             fi
         done
@@ -236,7 +258,7 @@ fnDiff() {
         if ! fnUmount; then
             RESULT=1
         fi
-    fi;
+    fi
     return "${RESULT}"
 }
 
@@ -249,24 +271,24 @@ fnRotate() {
     local NEW
     local OLD
 
-    while [ "${N}" -gt "1" ]; do
-        local NEW="${BASE}.`printf '%02d' ${N}`"
-        N=`expr ${N} - 1`
-        local OLD="${BASE}.`printf '%02d' ${N}`"
+    while [[ "${N}" -gt "1" ]]; do
+        printf -v NEW '%s.%02d' "${BASE}" "${N}"
+        ((N--))
+        printf -v OLD '%s.%02d' "${BASE}" "${N}"
 
-        if [ -d "${NEW}" ]; then
+        if [[ -d "${NEW}" ]]; then
             echo "rm -rf ${NEW}"
             rm -rf "${NEW}"
-            if [ "$?" -ne "0" ]; then
+            if [[ "$?" -ne "0" ]]; then
                 echo '**** ERROR REMOVING DIRECTORY ****' 1>&2
                 return 1
             fi
         fi
 
-        if [ -d "${OLD}" ]; then
+        if [[ -d "${OLD}" ]]; then
             echo "mv -f ${OLD} ${NEW}"
             mv -f "${OLD}" "${NEW}"
-            if [ "$?" -ne "0" ]; then
+            if [[ "$?" -ne "0" ]]; then
                 echo '**** ERROR MOVING DIRECTORY ****' 1>&2
                 return 1
             fi
@@ -278,96 +300,80 @@ fnMkCheckpoint() {
     local PTNAME="${1}"
     local PTCNT="${2}"
 
-    fnRotate "${ROOT}" "${PTNAME}"  "${PTCNT}"
-    echo "cp -al ${HEAD} ${ROOT}/${PTNAME}.01"
-    cp -al "${HEAD}" "${ROOT}/${PTNAME}.01"
+    if [[ "${PTCNT}" -gt "0" ]]; then
+        echo "-- CREATE CHECKPOINT ${PTNAME} --"
+        fnRotate "${ROOT}" "${PTNAME}" "${PTCNT}"
+        echo "cp -al ${HEAD} ${ROOT}/${PTNAME}.01"
+        cp -al "${HEAD}" "${ROOT}/${PTNAME}.01"
+    fi
 }
 
 fnStart() {
-    local RESULT="0";
-    if [ ! -d "${MOUNT}" ]; then
-        echo "**** MOUNT POINT NOT FOUND ${MOUNT} ****" 1>&2
+    local RESULT="0"
+    if ! fnMount; then
         RESULT=1
     else
-        if ! fnIsAvailable "${DEVICE_REAL}"; then
-            echo "**** ${DEVICE} IS NOT AVAILABLE ****" 1>&2
+        if [[ -d "${ROOT}" ]]; then
+            if [[ ! -d "${HEAD}" ]]; then
+                echo "-- CREATE HEAD DIRECTORY --"
+                echo "mkdir -m 0755 ${HEAD}"
+                mkdir -m 0755 -p "${HEAD}"
+            fi
+        fi
+
+        if [[ ! -d "${HEAD}" ]]; then
+            echo "**** HEAD PATH NOT FOUND ${HEAD} ****" 1>&2
             RESULT=1
         else
-            if fnIsMounted "${DEVICE_REAL}"; then
-                echo "**** ${DEVICE} IS ALREADY MOUNTED ****" 1>&2
+            local D=`find "${ROOT}/daily.01"   -maxdepth 0 -type d -mmin  +1430 2>/dev/null`
+            local W=`find "${ROOT}/weekly.01"  -maxdepth 0 -type d -mtime +6    2>/dev/null`
+            local M=`find "${ROOT}/monthly.01" -maxdepth 0 -type d -mtime +29   2>/dev/null`
+            local Y=`find "${ROOT}/yearly.01"  -maxdepth 0 -type d -mtime +364  2>/dev/null`
+
+            echo "-- RUNNING BACKUP COMMANDS --"
+            local CMD
+            for CMD in "${RSYNC[@]}"; do
+                echo "${CMD}"
+                $CMD
+                if [[ "$?" -ne "0" ]]; then
+                    RESULT=1
+                fi
+            done
+
+            if [[ "${RESULT}" -ne "0" ]]; then
+                echo '**** ERROR RUNNING BACKUP ****' 1>&2
                 RESULT=1
             else
-                fnMount
-                if [ "$?" -ne "0" ]; then
-                    echo '**** ERROR MOUNTING ${DEVICE} ****' 1>&2
-                    RESULT=1
-                else
-                    if [ ! -d "${ROOT}" ]; then
-                        echo "**** BACKUP ROOT NOT FOUND ${ROOT} ****" 1>&2
-                        RESULT=1
-                    else
+                echo "touch ${HEAD}"
+                touch "${HEAD}"
 
-                        local D=`find "${ROOT}" -maxdepth 1 -name daily.01   -type d -mmin  +1430 2>/dev/null`
-                        local W=`find "${ROOT}" -maxdepth 1 -name weekly.01  -type d -mtime +6    2>/dev/null`
-                        local M=`find "${ROOT}" -maxdepth 1 -name monthly.01 -type d -mtime +29   2>/dev/null`
-                        local Y=`find "${ROOT}" -maxdepth 1 -name yearly.01  -type d -mtime +364  2>/dev/null`
+                fnMkCheckpoint instant "${INSTANT}"
 
-                        if [ ! -d "${HEAD}" ]; then
-                            echo "mkdir -m 0755 -p ${HEAD}"
-                            mkdir -m 0755 -p "${HEAD}"
-                        fi
-
-                        echo "-- RUNNING BACKUP COMMANDS --"
-                        local CMD
-                        for CMD in "${RSYNC[@]}"; do
-                            echo "${CMD}"
-                            $CMD
-                            if [ "$?" -ne "0" ]; then
-                                RESULT=1
-                            fi
-                        done
-
-                        if [ "${RESULT}" -ne "0" ]; then
-                            echo '**** ERROR RUNNING BACKUP ****' 1>&2
-                            RESULT=1
-                        else
-                            echo "touch ${HEAD}"
-                            touch "${HEAD}"
-
-                            echo "-- CREATE INSTANT CHECKPOINT --"
-                            fnMkCheckpoint instant "${INSTANT}"
-
-                            if [ ! -d "${ROOT}/daily.01" -o -n "${D}" ]; then 
-                                echo "-- CREATE DAILY CHECKPOINT --"
-                                fnMkCheckpoint daily "${DAILY}"
-                            fi
-
-                            if [ ! -d "${ROOT}/weekly.01" -o -n "${W}" ]; then 
-                                echo "-- CREATE WEEKLY CHECKPOINT --"
-                                fnMkCheckpoint weekly "${WEEKLY}"
-                            fi
-
-                            if [ ! -d "${ROOT}/monthly.01" -o -n "${M}" ]; then 
-                                echo "-- CREATE MONTHLY CHECKPOINT --"
-                                fnMkCheckpoint monthly "${MONTHLY}"
-                            fi
-
-                            if [ ! -d "${ROOT}/yearly.01" -o -n "${Y}" ]; then 
-                                echo "-- CREATE YEARLY CHECKPOINT --"
-                                fnMkCheckpoint yearly "${YEARLY}"
-                            fi
-
-                            RESULT=$?
-                        fi
-                    fi
-
-                    echo 'sync; sync;'
-                    sync; sync;
-                    if ! fnUmount; then
-                        RESULT=1
-                    fi
+                if [[ ! -d "${ROOT}/daily.01" || -n "${D}" ]]; then 
+                    fnMkCheckpoint daily "${DAILY}"
                 fi
+
+                if [[ ! -d "${ROOT}/weekly.01" || -n "${W}" ]]; then 
+                    fnMkCheckpoint weekly "${WEEKLY}"
+                fi
+
+                if [[ ! -d "${ROOT}/monthly.01" || -n "${M}" ]]; then 
+                    fnMkCheckpoint monthly "${MONTHLY}"
+                fi
+
+                if [[ ! -d "${ROOT}/yearly.01" || -n "${Y}" ]]; then 
+                    fnMkCheckpoint yearly "${YEARLY}"
+                fi
+
+                RESULT=$?
             fi
+
+            echo 'sync; sync;'
+            sync; sync;
+        fi
+
+        if ! fnUmount; then
+            RESULT=1
         fi
     fi
     return "${RESULT}"
@@ -375,7 +381,7 @@ fnStart() {
 
 ########################################################################
 
-if [ "${OK}" != "YES" ]; then
+if [[ "${OK}" != "YES" ]]; then
     fnConfig
     exit 1
 fi
@@ -387,7 +393,7 @@ case "$1" in
         ;;
     help)
         fnHelp
-        exit 0;
+        exit 0
         ;;
     config)
         fnConfig
@@ -403,6 +409,10 @@ case "$1" in
         ;;
     diff)
         fnDiff
+        exit $?
+        ;;
+    ls)
+        fnLs
         exit $?
         ;;
     mount)
